.TH man 6 "29 Oct 2019" "1.0" "Create man page"
.SH NAME 
create This script provides the functionality of create \- Create new car
.SH SYNOPSIS 
bash create [license] [model] [color] [passengers]
.SH DESCRIPTION 
create is a bash program that allows to create a new car in Database 
.SH AUTHOR 
Programmer first name, last name 
