#!/bin/bash 

#this programs record a trip in the file of a car provided 
if [ $# -ne 2 ]; then 
         echo " error with the number of arguments"
	 echo "enter license distance"
	 exit 
fi 
km=$2 
license=$1 
#check if the file exist 
if [ ! -f "$license.txt" ]; then 
	 echo "car does not exist"
	 exit 
fi
echo "$km" >> $license.txt
bash frame1 "trip recorded successfully"
